/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beans;

import java.awt.Color;

/**
 *
 * @author florinoprea, williancieslak
 */
public class TrafficLightBean extends javax.swing.JPanel {

    private String title;
    private String subtitle;
    private Color top;
    private Color middle;
    private Color bottom;

    public TrafficLightBean() {
        this.title = "";
        this.subtitle = "";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trafficLight21 = new eu.hansolo.steelseries.extras.TrafficLight2();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        trafficLight21.add(jLabel2);
        jLabel2.setBounds(0, 210, 80, 20);

        jLabel1.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(trafficLight21, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trafficLight21, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setRed(Boolean b) {
        trafficLight21.setRedOn(b);
        jLabel2.setText("STOP");
    }

    public void setYellow(Boolean b) {
        trafficLight21.setYellowOn(b);
        jLabel2.setText("Attention");
    }

    public void setGreen(Boolean b) {
        trafficLight21.setGreenOn(b);
        jLabel2.setText("GO");
    }

    public void showGreen() {
        trafficLight21.setYellowOn(false);
        trafficLight21.setRedOn(false);
        trafficLight21.setGreenOn(true);
        jLabel2.setText("GO");
    }

    public void showYellow() {
        trafficLight21.setYellowOn(true);
        trafficLight21.setRedOn(false);
        trafficLight21.setGreenOn(false);
        jLabel2.setText("Attention");
    }

    public void showRed() {
        trafficLight21.setYellowOn(false);
        trafficLight21.setRedOn(true);
        trafficLight21.setGreenOn(false);
        jLabel2.setText("STOP");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private eu.hansolo.steelseries.extras.TrafficLight2 trafficLight21;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * @param title the title to set
     */
    public void setTitle(String title) {
        this.title = title;
        jLabel1.setText(title);
    }

    /**
     * @return the subtitle
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * @param subtitle the subtitle to set
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
        jLabel2.setText(subtitle);
    }

    public Color getTop() {
        return top;
    }

    public void setTop(Color top) {
        this.top = top;
    }

    public Color getMiddle() {
        return middle;
    }

    public void setMiddle(Color middle) {
        this.middle = middle;
    }

    public Color getBottom() {
        return bottom;
    }

    public void setBottom(Color bottom) {
        this.bottom = bottom;
    }
}
